### ISSUE TITLE
Replace Kotlin Android Extensions with View Binding

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/Umweltzone#126]
# Description

- All usage of the _Kotlin Android Extensions_ should be replaced with _View Binding_.
- When building the project then the following warning is output:

    > Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by fejd** [comment]
I'd like to work on this one.

**Comment by johnjohndoe** [comment]
Cool. Let me know if you have any questions.
