### ISSUE TITLE
Add Dutch translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/Umweltzone#38]
It would be nice to have a Dutch translation of the app. :netherlands: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/65762120-8babb580-e120-11e9-8277-29e21c5b9415.png)

# TODOs

- [x] Add new translations in `Umweltzone/src/main/res/values-nl/strings.xml` (ignore `config` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left
  - Do not translate `changelog.xml`.
  - Do append the German version of `zone_not_drawable_email_html_message` as done in `values/strings.xml`.
  - Do not add strings marked as `translatable="false"` to your files.
  - Escape special characters such as apostrophe `'` with their corresponding entity, e.g. `&#8217;`.
- [x] Optional: Add new translations for FAQs in `Umweltzone/src/main/res/raw/faqs_nl.json`
  - The English and German files can be found the `Umweltzone/src/main/res/raw/` folder.
  ![faqs](https://user-images.githubusercontent.com/144518/65762365-25736280-e121-11e9-9070-bf9ca34a182c.png)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- [Testing contributions](https://github.com/Umweltzone/Umweltzone/tree/rip-uservoice#testing)

**Comment by spmvanmierlo** [comment]
Hi, I would like to help you out with the dutch translations! Will be starting from 1st october.

**Comment by johnjohndoe** [comment]
@spmvanmierlo Sounds great. Please keep in mind that I won't be able to respond quickly since I will be on vacation soon.

**Comment by spmvanmierlo** [comment]
@johnjohndoe no problem! What period are you on vacation?

**Comment by johnjohndoe** [comment]
@spmvanmierlo Oct 3-31

**Comment by spmvanmierlo** [comment]
Created a pull request for this issue! !43

**Comment by johnjohndoe** [comment]
Resolved by 24b90fb25dbfe512e8514a88a43a0432950bb787.

**Comment by johnjohndoe** [comment]
@spmvanmierlo In case you have time there is a few more strings to translate: https://github.com/Umweltzone/roadsigns/issues
